Use myNewDB;

ALTER TABLE Students
    ADD ID INT;

UPDATE STUDENTS SET ID = 1 WHERE STUDENTNAME = "Jane Doe";
UPDATE STUDENTS SET ID = 2 WHERE STUDENTNAME = "APRIL HOWARD";
UPDATE STUDENTS SET ID = 3 WHERE STUDENTNAME = "Greg Howard";
UPDATE STUDENTS SET ID = 35 WHERE STUDENTNAME = "JOHNNY BOY";


UPDATE STUDENTS SET CITY = "Edinburgh", COUNTRY = "Scotland" WHERE ID = 35;;
UPDATE  STUDENTS SET CITY = "Edinburgh" WHERE COUNTRY = "Scotland";
SELECT * FROM Students;